/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  api: {
    v1: {
      users: {
        Registrations: () => import('#controllers/api/v1/users/registrations_controller'),
        Sessions: () => import('#controllers/api/v1/users/sessions_controller'),
      },
    },
  },
  HealthChecks: () => import('#controllers/health_checks_controller'),
}
