/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from "@adonisjs/lucid/orm";
import { DateTime } from "luxon";

export class UserSchema extends BaseModel {
  static $columns = [
    "id",
    "email",
    "password",
    "firstName",
    "lastName",
    "createdAt",
    "updatedAt",
  ] as const;
  $columns = UserSchema.$columns;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare email: string;
  @column({ serializeAs: null })
  declare password: string;
  @column()
  declare firstName: string;
  @column()
  declare lastName: string;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
}
