#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
  set -o xtrace
fi

NODE_ENV=development pnpm install && node ace migration:fresh && node ace migration:status && node ace db:seed
