name: CI
on:
  push:
    branches:
      - "**" # matches every branch
      - "!main"
  pull_request:
    branches:
      - "staging"

jobs:
  build:
    name: 🏗 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: latest

      - uses: pnpm/action-setup@v6
        with:
          version: 10.33.2

      - name: 🔧 Install modules
        run: pnpm install

      - name: ⚙️ Build app
        run: pnpm run build

  testing:
    name: 🧪 Testing
    if: success()
    needs: build
    runs-on: ubuntu-latest

    # Postgres service
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: developer
          POSTGRES_DB: adonisjs_boilerplate_test
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: latest

      - uses: pnpm/action-setup@v6
        with:
          version: 10.33.2

      - name: 🔧 Install modules
        run: pnpm install

      - name: 🧪 Run tests
        shell: bash
        run: bash ./scripts/test

  linters:
    name: 🔬 Linters
    if: success()
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: latest

      - uses: pnpm/action-setup@v6
        with:
          version: 10.33.2

      - name: 🔧 Install modules
        run: pnpm install

      - name: 🔬 Run Oxlint
        run: pnpm run lint

  licenses:
    name: ©️ Licenses
    if: success()
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: 🔧 Checkout code
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: latest

      - uses: pnpm/action-setup@v6
        with:
          version: 10.33.2

      - name: 🔧 Install modules
        run: pnpm install

      - name: 🧪 Run licenses check
        shell: bash
        run: bash ".github/scripts/check-licenses.sh"
