name: staging-deploy
on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [staging]

jobs:
  deploy:
    name: 🚀 Deploy to Render
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false
